### ISSUE TITLE
Gitlab testing started failing

### ISSUE THREAD

**Issue by Keesromkes** [nunomaduro/phpinsights#262]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? |no
| Library version  | 1.9.0

I've been doing a bit of testing through gitlab instead of on my development machine, but recently it doesn't seem to work anymore. 

This is the error I have:

```
Fatal error: Uncaught Error: Class 'NunoMaduro\PhpInsights\Application\Console\Formatters\FormatResolver' not found in /builds/keesromkes/EK-backend/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/AnalyseCommand.php:68
Stack trace:
#0 [internal function]: NunoMaduro\PhpInsights\Application\Console\Commands\AnalyseCommand->__invoke(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 /builds/keesromkes/EK-backend/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/InvokableCommand.php(36): call_user_func(Object(NunoMaduro\PhpInsights\Application\Console\Commands\AnalyseCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /builds/keesromkes/EK-backend/vendor/symfony/console/Command/Command.php(255): NunoMaduro\PhpInsights\Application\Console\Commands\InvokableCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutp in /builds/keesromkes/EK-backend/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/AnalyseCommand.php on line 68
ERROR: Job failed: exit code 1

```

And this is the Gitlab CI I'm using to run the test;

```insight:
  image: php:7.3.7
  stage: test
  before_script:
    - apt-get update -qy
    - apt-get install zip unzip
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php composer-setup.php
    - php -r "unlink('composer-setup.php');"
    - php composer.phar install
    - php composer.phar require nunomaduro/phpinsights --dev
  script:
    - vendor/bin/phpinsights -vv -n --min-complexity=80 --min-architecture=80 --min-style=80 --min-quality=80
  allow_failure: true```

Locally it all works fine, so the pressure isn't high - but I'd love to keep my standards high, which is where PHPinsights comes to mind :-)

**Comment by olivernybroe** [comment]
Hmm, it sounds like your vendor folder has gotten corrupt, try deleting the vendor folder and see if that fixes it.

**Comment by Keesromkes** [comment]
> Hmm, it sounds like your vendor folder has gotten corrupt, try deleting the vendor folder and see if that fixes it.

so it was a bit more complicated than that (my local test had no problem) but my gitlab branch still had an old vendor folder in there. That overruled the creation of a new one apparantly!

Thanks for the support @olivernybroe, that did the trick then :-)

**Comment by olivernybroe** [comment]
@Keesromkes No problem! 
Nice that you found out what the exact problem was.
