### ISSUE TITLE
File/File.php calls activeSniff before it is set

### ISSUE THREAD

**Issue by jrmadsen67** [nunomaduro/phpinsights#350]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Library version  | ^1.7

Tracing this, the problem seems to be:
- Domain/File.php -> parse() is called at the top of -> process()
- in my case, it is choking on the line ending check, which calls ->addWarningOnLine(), which in turn calls -> addMessage() BUT...
- -> addMessage() is overwritten in Domain/File.php which uses ->activeSniff ... which isn't set until after the ->parse() from above

I'll poke around a little more for a quick workaround & confirm that is the issue; I'm new to Insights (today) so may need a little time to track it all down 

Here is the dump:
```
[2020-02-02 16:40:12] local.ERROR: Call to a member function addDetails() on null {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function addDetails() on null at /home/vagrant/Code/Madera/vendor/nunomaduro/phpinsights/src/Domain/File.php:139)
[stacktrace]
#0 /home/vagrant/Code/Madera/vendor/squizlabs/php_codesniffer/src/Files/File.php(752): NunoMaduro\\PhpInsights\\Domain\\File->addMessage(false, 'File has mixed ...', 1, 1, 'Internal.LineEn...', Array, 0, false)
#1 /home/vagrant/Code/Madera/vendor/squizlabs/php_codesniffer/src/Files/File.php(591): PHP_CodeSniffer\\Files\\File->addWarningOnLine('File has mixed ...', 1, 'Internal.LineEn...')
#2 /home/vagrant/Code/Madera/vendor/nunomaduro/phpinsights/src/Domain/File.php(54): PHP_CodeSniffer\\Files\\File->parse()
#3 /home/vagrant/Code/Madera/vendor/nunomaduro/phpinsights/src/Domain/File.php(111): NunoMaduro\\PhpInsights\\Domain\\File->process()
#4 /home/vagrant/Code/Madera/vendor/nunomaduro/phpinsights/src/Domain/FileProcessors/SniffFileProcessor.php(61): NunoMaduro\\PhpInsights\\Domain\\File->processWithTokenListenersAndFileInfo(Array, Object(Symfony\\Component\\Finder\\SplFileInfo))
#5 /home/vagrant/Code/Madera/vendor/nunomaduro/phpinsights/src/Domain/Runner.php(97): NunoMaduro\\PhpInsights\\Domain\\FileProcessors\\SniffFileProcessor->processFile(Object(Symfony\\Component\\Finder\\SplFileInfo))
#6 /home/vagrant/Code/Madera/vendor/nunomaduro/phpinsights/src/Domain/Runner.php(83): NunoMaduro\\PhpInsights\\Domain\\Runner->processFile(Object(Symfony\\Component\\Finder\\SplFileInfo))
#7 /home/vagrant/Code/Madera/vendor/nunomaduro/phpinsights/src/Domain/Insights/InsightFactory.php(110): NunoMaduro\\PhpInsights\\Domain\\Runner->run()
#8 /home/vagrant/Code/Madera/vendor/nunomaduro/phpinsights/src/Domain/Insights/InsightFactory.php(78): NunoMaduro\\PhpInsights\\Domain\\Insights\\InsightFactory->runInsightCollector(Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#9 /home/vagrant/Code/Madera/vendor/nunomaduro/phpinsights/src/Domain/Insights/InsightCollectionFactory.php(85): NunoMaduro\\PhpInsights\\Domain\\Insights\\InsightFactory->makeFrom('ObjectCalisthen...', Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#10 [internal function]: NunoMaduro\\PhpInsights\\Domain\\Insights\\InsightCollectionFactory->NunoMaduro\\PhpInsights\\Domain\\Insights\\{closure}('ObjectCalisthen...')
#11 /home/vagrant/Code/Madera/vendor/nunomaduro/phpinsights/src/Domain/Insights/InsightCollectionFactory.php(91): array_map(Object(Closure), Array)
#12 /home/vagrant/Code/Madera/vendor/nunomaduro/phpinsights/src/Application/Console/Analyser.php(58): NunoMaduro\\PhpInsights\\Domain\\Insights\\InsightCollectionFactory->get(Array, Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#13 /home/vagrant/Code/Madera/vendor/nunomaduro/phpinsights/src/Application/Console/Commands/AnalyseCommand.php(60): NunoMaduro\\PhpInsights\\Application\\Console\\Analyser->analyse(Object(NunoMaduro\\PhpInsights\\Application\\Console\\Formatters\\Console), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#14 /home/vagrant/Code/Madera/vendor/nunomaduro/phpinsights/src/Application/Adapters/Laravel/Commands/InsightsCommand.php(51): NunoMaduro\\PhpInsights\\Application\\Console\\Commands\\AnalyseCommand->__invoke(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#15 [internal function]: NunoMaduro\\PhpInsights\\Application\\Adapters\\Laravel\\Commands\\InsightsCommand->handle()
#16 /home/vagrant/Code/Madera/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#17 /home/vagrant/Code/Madera/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#18 /home/vagrant/Code/Madera/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#19 /home/vagrant/Code/Madera/vendor/laravel/framework/src/Illuminate/Container/Container.php(576): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#20 /home/vagrant/Code/Madera/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#21 /home/vagrant/Code/Madera/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#22 /home/vagrant/Code/Madera/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#23 /home/vagrant/Code/Madera/vendor/symfony/console/Application.php(1012): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#24 /home/vagrant/Code/Madera/vendor/symfony/console/Application.php(272): Symfony\\Component\\Console\\Application->doRunCommand(Object(NunoMaduro\\PhpInsights\\Application\\Adapters\\Laravel\\Commands\\InsightsCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#25 /home/vagrant/Code/Madera/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#26 /home/vagrant/Code/Madera/vendor/laravel/framework/src/Illuminate/Console/Application.php(90): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#27 /home/vagrant/Code/Madera/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(133): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#28 /home/vagrant/Code/Madera/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#29 {main}
"}

<!--
Love PHP Insights? Please consider supporting us via Patreon or OpenCollective:
👉  https://www.patreon.com/nunomaduro
👉  https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=66BYDWAT92N6L
--
```

**Comment by olivernybroe** [comment]
I have not been able to reproduce this.   
Is this still happening for you?

**Comment by jrmadsen67** [comment]
Hi Oliver!

To trigger this error you will need to have a file with mixed line endings, to trigger this warning in code_sniffer/ Files/File.php

![image](https://user-images.githubusercontent.com/821958/76128582-0d94f880-6048-11ea-822a-9f488fbbd999.png)

One that is triggered, I think it is easier to make sense of my notes above - you'll see that the way Insights has overridden `addMessage()`, it is trying to use ->activeSniff before that is set

Thanks!

**Comment by jiasilu** [comment]
I've encountered the same error as well. @jrmadsen67 Were you able to find a workaround? Thanks!

**Comment by jrmadsen67** [comment]
I'm afraid I can't remember - I think I just manually tracked the one file
that was giving us the issue & cleaned it, or some temp solution like that

**Comment by jiasilu** [comment]
@jrmadsen67 Appreciate it, thx!

**Comment by JustSteveKing** [comment]
Gone stale, closing for now
