### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by mauxtin** [nunomaduro/phpinsights#41]
First of all, great work with the package 🥇 

Just wanted to let you know that when running on windows (bash) the package doesn't work. It only works with Windows Linux subsystem

### What doesn't work
```
$ php ./vendor/bin/phpinsights

dir=$(cd "${0%[/\\]*}" > /dev/null; cd "../nunomaduro/phpinsights/bin" && pwd)

if [ -d /proc/cygdrive ]; then
    case $(which php) in
        $(readlink -n /proc/cygdrive)/*)
            # We are in Cygwin using Windows php, so the path must be translated
            dir=$(cygpath -m "$dir");
            ;;
    esac
fi

"${dir}/phpinsights" "$@"
```
```
$ php artisan insights

[2019-05-14 11:27:49] local.ERROR: The file `composer.json` must exist. You should run PHP Insights from the root of your project. {"exception":"[object] (RuntimeException(code: 0): The file `composer.json` must exist. You should run PHP Insights from the root of your project. at D:\\Code\\xxxxx\\vendor\
unomaduro\\phpinsights\\src\\Application\\Console\\Commands\\AnalyseCommand.php:64)
[stacktrace]
#0 D:\\Code\\xxxxx\\vendor\
unomaduro\\phpinsights\\src\\Application\\Adapters\\Laravel\\Commands\\InsightsCommand.php(43): NunoMaduro\\PhpInsights\\Application\\Console\\Commands\\AnalyseCommand->__invoke(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#1 [internal function]: NunoMaduro\\PhpInsights\\Application\\Adapters\\Laravel\\Commands\\InsightsCommand->handle(Object(NunoMaduro\\PhpInsights\\Application\\Console\\Commands\\AnalyseCommand))
#2 D:\\Code\\xxxxx\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(32): call_user_func_array(Array, Array)
#3 D:\\Code\\xxxxx\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(90): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#4 D:\\Code\\xxxxx\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#5 D:\\Code\\xxxxx\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(576): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#6 D:\\Code\\xxxxx\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(183): Illuminate\\Container\\Container->call(Array)
#7 D:\\Code\\xxxxx\\vendor\\symfony\\console\\Command\\Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#8 D:\\Code\\xxxxx\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#9 D:\\Code\\xxxxx\\vendor\\symfony\\console\\Application.php(908): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#10 D:\\Code\\xxxxx\\vendor\\symfony\\console\\Application.php(269): Symfony\\Component\\Console\\Application->doRunCommand(Object(NunoMaduro\\PhpInsights\\Application\\Adapters\\Laravel\\Commands\\InsightsCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#11 D:\\Code\\xxxxx\\vendor\\symfony\\console\\Application.php(145): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#12 D:\\Code\\xxxxx\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Application.php(90): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#13 D:\\Code\\xxxxx\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(122): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#14 D:\\Code\\xxxxx\\artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#15 {main}
"} 

```

Through Windows Linux Subsystem terminal:

```
$ php ./vendor/bin/phpinsights

//Same as first snippet

```

### What works:
Through Windows Linux Subsystem terminal:
```
$ php artisan insights

//Works!
```

Posting it mostly as a reference for anyone else who have trouble getting it to work. (Not sure if windows are meant to be supported anyway 😄 )

**Comment by nunomaduro** [comment]
@mauxtin Thanks for reporting this. I don't have a Windows machine. Let's wait, maybe someone can give us a hand on this and submit a pull request.

**Comment by nunomaduro** [comment]
Fixed on the version `v1.0.2`. https://github.com/nunomaduro/phpinsights/commit/8bae26f096f6f9e39e3dc2e6c03ec4acb4e3f802.

Please make sure you perform: `composer update nunomaduro/phpinsights` to get the latest version.

**Comment by galloaleonardo** [comment]
The above changes are contemplated in my version, but the error continues. =(

```
$ php ./vendor/bin/phpinsights

dir=$(cd "${0%[/\\]*}" > /dev/null; cd "../nunomaduro/phpinsights/bin" && pwd)

if [ -d /proc/cygdrive ]; then
    case $(which php) in
        $(readlink -n /proc/cygdrive)/*)
            # We are in Cygwin using Windows php, so the path must be translated
            dir=$(cygpath -m "$dir");
            ;;
    esac
fi

"${dir}/phpinsights" "$@"
```

**Comment by nunomaduro** [comment]
What error do you have exactly? @galloaleonardo

**Comment by galloaleonardo** [comment]
When I run the command: php ./vendor/bin/phpinsights
Is displayed:

```
dir=$(cd "${0%[/\\]*}" > /dev/null; cd "../nunomaduro/phpinsights/bin" && pwd)

if [ -d /proc/cygdrive ]; then
    case $(which php) in
        $(readlink -n /proc/cygdrive)/*)
            # We are in Cygwin using Windows php, so the path must be translated
            dir=$(cygpath -m "$dir");
            ;;
    esac
fi

"${dir}/phpinsights" "$@"
```

Should I parameterize something?

**Comment by mauxtin** [comment]
I can confirm that `$ php  ./vendor/bin/phpinsights` has the same effect as before however I just noticed that simply running `$ ./vendor/bin/phpinsights` (without the `php` in front) works fine on windows (outside the linux subsystem)

**Comment by nunomaduro** [comment]
@galloaleonardo Can you update the latest version and test again?

**Comment by galloaleonardo** [comment]
Thanks for the support, @nunomaduro and @mauxtin. Using `$ ./vendor/bin/phpinsights` without the php prefix the analysis is displayed (outside the linux subsystem).
Congratulations on the project! ;)

**Comment by leocavalcante** [comment]
Hi folks, if it helps to clarify:

Composer already handles Windows by it self:
https://getcomposer.org/doc/articles/vendor-binaries.md#what-about-windows-and-bat-files-

![image](https://user-images.githubusercontent.com/183722/57802011-731b9f80-772b-11e9-807b-40bf2a3f782f.png)

**Comment by nunomaduro** [comment]
Could someone make a pull request on readme about this?
