### ISSUE TITLE
PHP insights --fix flag does not work with multiple variations

### ISSUE THREAD

**Issue by prondubuisi** [nunomaduro/phpinsights#479]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Library version  | 1.14.1

Hello, I am trying to use the `--fix` flag with multiple variations and none of the commands seems to work 
This is what the official documentation recommends

```
# Classical command with --fix option
vendor/bin/phpinsights analyse path/to/analyse --fix

# In laravel
php artisan insights path/to/analyse --fix

# Just fix
vendor/bin/phpinsights fix path/to/analyse
```

Trying all the above commands says there is no command `fix`

```
Ndubuisis-MacBook-Pro:patricia-pay prondubuisi$ ./vendor/bin/phpinsights fix ./

                                 
  Command "fix" is not defined.  
                                 

Ndubuisis-MacBook-Pro:patricia-pay prondubuisi$ php artisan insights ./ --fix

                                      
  The "--fix" option does not exist.  
                                      

Ndubuisis-MacBook-Pro:patricia-pay prondubuisi$ 
```
Here is what I have tried extensively 
``` 
Ndubuisis-MacBook-Pro:patricia-pay prondubuisi$ php artisan insights analyse --help
Description:
  Analyze the code quality

Usage:
  insights [options] [--] [<directory>]

Arguments:
  directory                                  The directory to analyse

Options:
  -c, --config-path[=CONFIG-PATH]            The configuration file path [default: "config/insights.php"]
      --min-quality[=MIN-QUALITY]            Minimal Quality level to reach without throw error [default: 0]
      --min-complexity[=MIN-COMPLEXITY]      Minimal Complexity level to reach without throw error [default: 0]
      --min-architecture[=MIN-ARCHITECTURE]  Minimal Architecture level to reach without throw error [default: 0]
      --min-style[=MIN-STYLE]                Minimal Style level to reach without throw error [default: 0]
      --disable-security-check               Disable Security issues check to not throw error if vulnerability is found
      --format=FORMAT                        Format to output the result in [console, json, checkstyle] [default: ["console"]] (multiple values allowed)
  -h, --help                                 Display help for the given command. When no command is given display help for the list command
  -q, --quiet                                Do not output any message
  -V, --version                              Display this application version
      --ansi                                 Force ANSI output
      --no-ansi                              Disable ANSI output
  -n, --no-interaction                       Do not ask any interactive question
      --env[=ENV]                            The environment the command should run under
  -v|vv|vvv, --verbose                       Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug
Ndubuisis-MacBook-Pro:patricia-pay prondubuisi$ php artisan insights analyse ./

                                                                             
  Too many arguments to "insights" command, expected arguments "directory".  
                                                                             

Ndubuisis-MacBook-Pro:patricia-pay prondubuisi$ php artisan insights  ./
 164/257 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░]  63%
^C
Ndubuisis-MacBook-Pro:patricia-pay prondubuisi$ php artisan insights  ./ --fix

                                      
  The "--fix" option does not exist.  
                                      

Ndubuisis-MacBook-Pro:patricia-pay prondubuisi$ php artisan insights  fix

   NunoMaduro\PhpInsights\Domain\Exceptions\DirectoryNotFound 

  The "/Users/prondubuisi/gitrepos/patricia-pay/fix" directory does not exist.

  at vendor/nunomaduro/phpinsights/src/Domain/Insights/InsightCollectionFactory.php:69
     65▕             $files = array_map(static function (\SplFileInfo $file) {
     66▕                 return $file->getRealPath();
     67▕             }, iterator_to_array($this->filesRepository->within($dir, $this->config->getExcludes())->getFiles()));
     68▕         } catch (\InvalidArgumentException $exception) {
  ➜  69▕             throw new DirectoryNotFound($exception->getMessage(), 0, $exception);
     70▕         }
     71▕ 
     72▕         $collector = $this->analyser->analyse($dir, $files);
     73▕ 

      +19 vendor frames 
  20  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
Ndubuisis-MacBook-Pro:patricia-pay prondubuisi$ php artisan insights  ./ fix

                                                                             
  Too many arguments to "insights" command, expected arguments "directory".  
                                                                             

Ndubuisis-MacBook-Pro:patricia-pay prondubuisi$ php artisan insights  fix ./

                                                                             
  Too many arguments to "insights" command, expected arguments "directory".  
                                                                             

Ndubuisis-MacBook-Pro:patricia-pay prondubuisi$ php artisan insights  fix 

   NunoMaduro\PhpInsights\Domain\Exceptions\DirectoryNotFound 

  The "/Users/prondubuisi/gitrepos/patricia-pay/fix" directory does not exist.

  at vendor/nunomaduro/phpinsights/src/Domain/Insights/InsightCollectionFactory.php:69
     65▕             $files = array_map(static function (\SplFileInfo $file) {
     66▕                 return $file->getRealPath();
     67▕             }, iterator_to_array($this->filesRepository->within($dir, $this->config->getExcludes())->getFiles()));
     68▕         } catch (\InvalidArgumentException $exception) {
  ➜  69▕             throw new DirectoryNotFound($exception->getMessage(), 0, $exception);
     70▕         }
     71▕ 
     72▕         $collector = $this->analyser->analyse($dir, $files);
     73▕ 

      +19 vendor frames 
  20  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
Ndubuisis-MacBook-Pro:patricia-pay prondubuisi$ ./vendor/bin/phpinsights
  52/257 [▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░░░░]  20%
^C
Ndubuisis-MacBook-Pro:patricia-pay prondubuisi$ ./vendor/bin/phpinsights fix

                                 
  Command "fix" is not defined.  
                                 

Ndubuisis-MacBook-Pro:patricia-pay prondubuisi$ ./vendor/bin/phpinsights fix ./

                                 
  Command "fix" is not defined.  
                                 

Ndubuisis-MacBook-Pro:patricia-pay prondubuisi$ ./vendor/bin/phpinsights --fix 
PHP Fatal error:  Uncaught Symfony\Component\Console\Exception\RuntimeException: The "--fix" option does not exist. in /Users/prondubuisi/gitrepos/patricia-pay/vendor/symfony/console/Input/ArgvInput.php:212
Stack trace:
#0 /Users/prondubuisi/gitrepos/patricia-pay/vendor/symfony/console/Input/ArgvInput.php(142): Symfony\Component\Console\Input\ArgvInput->addLongOption('fix', NULL)
#1 /Users/prondubuisi/gitrepos/patricia-pay/vendor/symfony/console/Input/ArgvInput.php(76): Symfony\Component\Console\Input\ArgvInput->parseLongOption('--fix')
#2 /Users/prondubuisi/gitrepos/patricia-pay/vendor/symfony/console/Input/Input.php(55): Symfony\Component\Console\Input\ArgvInput->parse()
#3 /Users/prondubuisi/gitrepos/patricia-pay/vendor/nunomaduro/phpinsights/src/Application/Injectors/Configuration.php(34): Symfony\Component\Console\Input\Input->bind(Object(Symfony\Component\Console\Input\InputDefinition))
#4 [internal function]: NunoMaduro\PhpInsights\Application\Injectors\Configuration::NunoMaduro\PhpInsights\Application\Injectors\{closur in /Users/prondubuisi/gitrepos/patricia-pay/vendor/symfony/console/Input/ArgvInput.php on line 212

Fatal error: Uncaught Symfony\Component\Console\Exception\RuntimeException: The "--fix" option does not exist. in /Users/prondubuisi/gitrepos/patricia-pay/vendor/symfony/console/Input/ArgvInput.php:212
Stack trace:
#0 /Users/prondubuisi/gitrepos/patricia-pay/vendor/symfony/console/Input/ArgvInput.php(142): Symfony\Component\Console\Input\ArgvInput->addLongOption('fix', NULL)
#1 /Users/prondubuisi/gitrepos/patricia-pay/vendor/symfony/console/Input/ArgvInput.php(76): Symfony\Component\Console\Input\ArgvInput->parseLongOption('--fix')
#2 /Users/prondubuisi/gitrepos/patricia-pay/vendor/symfony/console/Input/Input.php(55): Symfony\Component\Console\Input\ArgvInput->parse()
#3 /Users/prondubuisi/gitrepos/patricia-pay/vendor/nunomaduro/phpinsights/src/Application/Injectors/Configuration.php(34): Symfony\Component\Console\Input\Input->bind(Object(Symfony\Component\Console\Input\InputDefinition))
#4 [internal function]: NunoMaduro\PhpInsights\Application\Injectors\Configuration::NunoMaduro\PhpInsights\Application\Injectors\{closur in /Users/prondubuisi/gitrepos/patricia-pay/vendor/symfony/console/Input/ArgvInput.php on line 212
Ndubuisis-MacBook-Pro:patricia-pay prondubuisi$ ./vendor/bin/phpinsights analyse ./ --fix
PHP Fatal error:  Uncaught Symfony\Component\Console\Exception\RuntimeException: The "--fix" option does not exist. in /Users/prondubuisi/gitrepos/patricia-pay/vendor/symfony/console/Input/ArgvInput.php:212
Stack trace:
#0 /Users/prondubuisi/gitrepos/patricia-pay/vendor/symfony/console/Input/ArgvInput.php(142): Symfony\Component\Console\Input\ArgvInput->addLongOption('fix', NULL)
#1 /Users/prondubuisi/gitrepos/patricia-pay/vendor/symfony/console/Input/ArgvInput.php(76): Symfony\Component\Console\Input\ArgvInput->parseLongOption('--fix')
#2 /Users/prondubuisi/gitrepos/patricia-pay/vendor/symfony/console/Input/Input.php(55): Symfony\Component\Console\Input\ArgvInput->parse()
#3 /Users/prondubuisi/gitrepos/patricia-pay/vendor/nunomaduro/phpinsights/src/Application/Injectors/Configuration.php(34): Symfony\Component\Console\Input\Input->bind(Object(Symfony\Component\Console\Input\InputDefinition))
#4 [internal function]: NunoMaduro\PhpInsights\Application\Injectors\Configuration::NunoMaduro\PhpInsights\Application\Injectors\{closur in /Users/prondubuisi/gitrepos/patricia-pay/vendor/symfony/console/Input/ArgvInput.php on line 212

Fatal error: Uncaught Symfony\Component\Console\Exception\RuntimeException: The "--fix" option does not exist. in /Users/prondubuisi/gitrepos/patricia-pay/vendor/symfony/console/Input/ArgvInput.php:212
Stack trace:
#0 /Users/prondubuisi/gitrepos/patricia-pay/vendor/symfony/console/Input/ArgvInput.php(142): Symfony\Component\Console\Input\ArgvInput->addLongOption('fix', NULL)
#1 /Users/prondubuisi/gitrepos/patricia-pay/vendor/symfony/console/Input/ArgvInput.php(76): Symfony\Component\Console\Input\ArgvInput->parseLongOption('--fix')
#2 /Users/prondubuisi/gitrepos/patricia-pay/vendor/symfony/console/Input/Input.php(55): Symfony\Component\Console\Input\ArgvInput->parse()
#3 /Users/prondubuisi/gitrepos/patricia-pay/vendor/nunomaduro/phpinsights/src/Application/Injectors/Configuration.php(34): Symfony\Component\Console\Input\Input->bind(Object(Symfony\Component\Console\Input\InputDefinition))
#4 [internal function]: NunoMaduro\PhpInsights\Application\Injectors\Configuration::NunoMaduro\PhpInsights\Application\Injectors\{closur in /Users/prondubuisi/gitrepos/patricia-pay/vendor/symfony/console/Input/ArgvInput.php on line 212
Ndubuisis-MacBook-Pro:patricia-pay prondubuisi$ 
```

**Comment by 50bhan** [comment]
@prondubuisi Yes, you are right. It's because you're using the `1.14.1` version and there is no fix option. You can use `dev-master` or wait for the V2.0 release.

You can see the required version In docs: https://phpinsights.com/get-started.html#fixing-errors-automatically

**Comment by prondubuisi** [comment]
Thanks, @50bhan.  Closing this now.
