### ISSUE TITLE
Use of undefined constant ICONV_IMPL - assumed 'ICONV_IMPL'

### ISSUE THREAD

**Issue by LorenzoLeonardini** [nunomaduro/phpinsights#72]
I've just installed phpinsights with the `composer require` command, but when I run the binary a huge error comes out:
```
PHP Warning:  Use of undefined constant ICONV_IMPL - assumed 'ICONV_IMPL' (this will throw an Error in a future version of PHP) in ./vendor/nette/utils/src/Utils/Strings.php on line 171
PHP Stack trace:
PHP   1. {main}() ./vendor/nunomaduro/phpinsights/bin/phpinsights:0
PHP   2. {closure:./vendor/nunomaduro/phpinsights/bin/phpinsights:10-37}() ./vendor/nunomaduro/phpinsights/bin/phpinsights:37
PHP   3. Symfony\Component\Console\Application->run() ./vendor/nunomaduro/phpinsights/bin/phpinsights:36
PHP   4. Symfony\Component\Console\Application->doRun() ./vendor/symfony/console/Application.php:145
PHP   5. Symfony\Component\Console\Application->doRunCommand() ./vendor/symfony/console/Application.php:269
PHP   6. NunoMaduro\PhpInsights\Application\Console\Commands\InvokableCommand->run() ./vendor/symfony/console/Application.php:908
PHP   7. NunoMaduro\PhpInsights\Application\Console\Commands\InvokableCommand->execute() ./vendor/symfony/console/Command/Command.php:255
PHP   8. call_user_func:{./vendor/nunomaduro/phpinsights/src/Application/Console/Commands/InvokableCommand.php:39}() ./vendor/nunomaduro/phpinsights/src/Application/Console/Commands/InvokableCommand.php:39
PHP   9. NunoMaduro\PhpInsights\Application\Console\Commands\AnalyseCommand->__invoke() ./vendor/nunomaduro/phpinsights/src/Application/Console/Commands/InvokableCommand.php:39
PHP  10. NunoMaduro\PhpInsights\Application\Console\Analyser->analyse() ./vendor/nunomaduro/phpinsights/src/Application/Console/Commands/AnalyseCommand.php:68
PHP  11. NunoMaduro\PhpInsights\Domain\Insights\InsightCollectionFactory->get() ./vendor/nunomaduro/phpinsights/src/Application/Console/Analyser.php:43
PHP  12. array_map() ./vendor/nunomaduro/phpinsights/src/Domain/Insights/InsightCollectionFactory.php:79
PHP  13. NunoMaduro\PhpInsights\Domain\Insights\InsightCollectionFactory::NunoMaduro\PhpInsights\Domain\Insights\{closure:./vendor/nunomaduro/phpinsights/src/Domain/Insights/InsightCollectionFactory.php:69-79}() ./vendor/nunomaduro/phpinsights/src/Domain/Insights/InsightCollectionFactory.php:79
PHP  14. NunoMaduro\PhpInsights\Domain\Insights\InsightFactory->makeFrom() ./vendor/nunomaduro/phpinsights/src/Domain/Insights/InsightCollectionFactory.php:73
PHP  15. NunoMaduro\PhpInsights\Domain\Insights\InsightFactory->getSniffCollector() ./vendor/nunomaduro/phpinsights/src/Domain/Insights/InsightFactory.php:71
PHP  16. League\Container\Container->get() ./vendor/nunomaduro/phpinsights/src/Domain/Insights/InsightFactory.php:175
PHP  17. League\Container\Definition\DefinitionAggregate->resolve() ./vendor/league/container/src/Container.php:153
PHP  18. League\Container\Definition\Definition->resolve() ./vendor/league/container/src/Definition/DefinitionAggregate.php:94
PHP  19. League\Container\Definition\Definition->resolveCallable() ./vendor/league/container/src/Definition/Definition.php:196
PHP  20. call_user_func_array:{./vendor/league/container/src/Definition/Definition.php:233}() ./vendor/league/container/src/Definition/Definition.php:233
PHP  21. NunoMaduro\PhpInsights\Application\Injectors\FileProcessors::NunoMaduro\PhpInsights\Application\Injectors\{closure:./vendor/nunomaduro/phpinsights/src/Application/Injectors/FileProcessors.php:28-51}() ./vendor/league/container/src/Definition/Definition.php:233
PHP  22. ContainerXTmLt2g\HttpKernelSymplify_EasyCodingStandard_HttpKernel_EasyCodingStandardKernelProd29074Container->get() ./vendor/nunomaduro/phpinsights/src/Application/Injectors/FileProcessors.php:31
PHP  23. ContainerXTmLt2g\HttpKernelSymplify_EasyCodingStandard_HttpKernel_EasyCodingStandardKernelProd29074Container->make() ./vendor/symfony/dependency-injection/Container.php:225
PHP  24. ContainerXTmLt2g\HttpKernelSymplify_EasyCodingStandard_HttpKernel_EasyCodingStandardKernelProd29074Container->load() ./vendor/symfony/dependency-injection/Container.php:243
PHP  25. require() /tmp/easy_coding_standard/ContainerXTmLt2g/HttpKernelSymplify_EasyCodingStandard_HttpKernel_EasyCodingStandardKernelProd29074Container.php:174
PHP  26. ContainerXTmLt2g\HttpKernelSymplify_EasyCodingStandard_HttpKernel_EasyCodingStandardKernelProd29074Container->load() /tmp/easy_coding_standard/ContainerXTmLt2g/getSniffFileProcessorService.php:9
PHP  27. require() /tmp/easy_coding_standard/ContainerXTmLt2g/HttpKernelSymplify_EasyCodingStandard_HttpKernel_EasyCodingStandardKernelProd29074Container.php:174
PHP  28. ContainerXTmLt2g\HttpKernelSymplify_EasyCodingStandard_HttpKernel_EasyCodingStandardKernelProd29074Container->load() /tmp/easy_coding_standard/ContainerXTmLt2g/getFileFactoryService.php:9
PHP  29. require() /tmp/easy_coding_standard/ContainerXTmLt2g/HttpKernelSymplify_EasyCodingStandard_HttpKernel_EasyCodingStandardKernelProd29074Container.php:174
PHP  30. ContainerXTmLt2g\HttpKernelSymplify_EasyCodingStandard_HttpKernel_EasyCodingStandardKernelProd29074Container->load() /tmp/easy_coding_standard/ContainerXTmLt2g/getErrorAndDiffCollectorService.php:9
PHP  31. require() /tmp/easy_coding_standard/ContainerXTmLt2g/HttpKernelSymplify_EasyCodingStandard_HttpKernel_EasyCodingStandardKernelProd29074Container.php:174
PHP  32. ContainerXTmLt2g\HttpKernelSymplify_EasyCodingStandard_HttpKernel_EasyCodingStandardKernelProd29074Container->load() /tmp/easy_coding_standard/ContainerXTmLt2g/getChangedFilesDetectorService.php:9
PHP  33. require() /tmp/easy_coding_standard/ContainerXTmLt2g/HttpKernelSymplify_EasyCodingStandard_HttpKernel_EasyCodingStandardKernelProd29074Container.php:174
PHP  34. ContainerXTmLt2g\HttpKernelSymplify_EasyCodingStandard_HttpKernel_EasyCodingStandardKernelProd29074Container->load() /tmp/easy_coding_standard/ContainerXTmLt2g/getTagAwareAdapterService.php:9
PHP  35. require() /tmp/easy_coding_standard/ContainerXTmLt2g/HttpKernelSymplify_EasyCodingStandard_HttpKernel_EasyCodingStandardKernelProd29074Container.php:174
PHP  36. ContainerXTmLt2g\HttpKernelSymplify_EasyCodingStandard_HttpKernel_EasyCodingStandardKernelProd29074Container->load() /tmp/easy_coding_standard/ContainerXTmLt2g/getSimpleCacheAdapterService.php:9
PHP  37. require() /tmp/easy_coding_standard/ContainerXTmLt2g/HttpKernelSymplify_EasyCodingStandard_HttpKernel_EasyCodingStandardKernelProd29074Container.php:174
PHP  38. Symplify\EasyCodingStandard\ChangedFilesDetector\Cache\Simple\FilesystemCacheFactory->create() /tmp/easy_coding_standard/ContainerXTmLt2g/getFilesystemCacheService.php:9
PHP  39. Nette\Utils\Strings::webalize() ./vendor/symplify/easy-coding-standard/packages/ChangedFilesDetector/src/Cache/Simple/FilesystemCacheFactory.php:22
PHP  40. Nette\Utils\Strings::toAscii() ./vendor/nette/utils/src/Utils/Strings.php:201
PHP Fatal error:  Uncaught Error: Call to undefined function Nette\Utils\iconv() in ./vendor/nette/utils/src/Utils/Strings.php:185
Stack trace:
#0 ./vendor/nette/utils/src/Utils/Strings.php(201): Nette\Utils\Strings::toAscii('/opt/lampp/htdo...')
#1 ./vendor/symplify/easy-coding-standard/packages/ChangedFilesDetector/src/Cache/Simple/FilesystemCacheFactory.php(22): Nette\Utils\Strings::webalize('/opt/lampp/htdo...')
#2 /tmp/easy_coding_standard/ContainerXTmLt2g/getFilesystemCacheService.php(9): Symplify\EasyCodingStandard\ChangedFilesDetector\Cache\Simple\FilesystemCacheFactory->create()
#3 /tmp/easy_coding_standard/ContainerXTmLt2g/HttpKernelSymplify_EasyCodingStandard_HttpKernel_EasyCodingStandardKernelProd29074Container.php(174): require('/tmp/easy_codin...')
#4 /tmp/easy_coding_standard/ContainerXTmLt2g/getSimpleCacheAdapterService.php(9): ContainerXTmLt2g\HttpKernelSymplify_EasyCodingStandard_HttpKernel_EasyCodingStandardKernelProd29074Container->l in ./vendor/nette/utils/src/Utils/Strings.php on line 185
```

I have a "vanilla" php project, with just some composer library.

Thank you for your help

**Comment by deleugpn** [comment]
Do you have php7-iconv installed?

**Comment by LorenzoLeonardini** [comment]
Thank you, that solved it. I thought it was in some way connected to the `Nette\Utils\Strings` error.
